### PR TITLE
Various bug fixes

### PR DESCRIPTION
**Pull request by jlindgren90**
Hi Simson,

First, thank you for your work on afflib.  We are using the library in a commercial data recovery/imaging product and have encountered various problems (mostly related to error handling) along the way.  Here are the changes we've made to fix said problems.  Please feel free to merge all of them or pick and choose, as you like.

Sincerely,
John Lindgren
CPR Tools, Inc.

### CODE REVIEW

**Comment by simsong** [comment]
Thanks for all of your help! I'm glad that this has been useful to you. I was surprised that the AFF compression files had to be recovered; why did you need to do that?

**Comment by jlindgren90** [comment]
We needed to support appending to and overwriting parts of an existing image file (for example, if the imaging process was interrupted halfway through), and in that case we wanted to use the same compression settings that were used when originally creating the image.

**Comment by simsong** [comment]
Ah. Why not just store the information in another AFF segment?

**Comment by jlindgren90** [comment]
That could work too.

**Pull request merged**
